### ISSUE TITLE
Instalation problem

### ISSUE THREAD

**Issue by yanchogeorgiev** [SocialiteProviders/Xing#1]
Hi,
Just tried to install xing provider on laravel 5 framework. I followed all instructions from the documentation. But when i try this: Socialite::with('xing') throw an error message:

InvalidArgumentException in Manager.php line 92: Driver [xing] not supported.

    in Manager.php line 92
    at Manager->createDriver('xing') in Manager.php line 62
    at Manager->driver('xing') in SocialiteManager.php line 26
    at SocialiteManager->with('xing') in Facade.php line 210
    at Facade::__callStatic('with', array('xing')) in AuthController.php line 40
    at Socialite::with('xing') in AuthController.php line 40
    at AuthController->redirectToProvider(...

Can you help me please?
Thanks,
Yancho

**Comment by DraperStudio** [comment]
Just pulled in the provider and everything went fine.

How do your files look that are mentioned in the documentation?

**Comment by yanchogeorgiev** [comment]
Thanks for the fast response!
Sorry, I'm a new in laravel 5 framework. Just installed laravel and xing provider with compressor and followed this installation steps: http://socialiteproviders.github.io/providers/xing/

This is all that i did:
1. Installed with laravel new xing command and after that installed "socialiteproviders/xing": "~1.0"
2. There wasn't Laravel\Socialite\SocialiteServiceProvider in my $provider variable so here i didn't do nothing.
3. Added 'SocialiteProviders\Manager\ServiceProvider', in config/app.php
4. EventServiceProvider $listen looks like this:
        protected $listen = [
		'SocialiteProviders\Manager\SocialiteWasCalled' => [
			// add your listeners (aka providers) here
		],
	];
5. Added xing credentials here: config/services.php
6. Added this to alias:
'Socialite'	=> 'Laravel\Socialite\Facades\Socialite'
7. Added route to social login
Route::get('sociallogin', 'Auth\AuthController@redirectToProvider');
8. In the Auth controller added following method:
       public function redirectToProvider()
	{
		var_dump(\Socialite::with('xing'));die;
		return \Socialite::with('xing')->redirect();
	}

Maybe I miss something?

**Comment by DraperStudio** [comment]
The listener array  in the EventServiceProvider.php should look like this. Then it should work.

```php
protected $listen = [
    `SocialiteProviders\Manager\SocialiteWasCalled` => [
        'SocialiteProviders\Xing\XingExtendSocialite@handle',.
    ],
];
```

**Comment by yanchogeorgiev** [comment]
Works, Thank you very much!
