### ISSUE TITLE
API Call

### ISSUE THREAD

**Issue by yanchogeorgiev** [SocialiteProviders/Xing#2]
Hi,
Is it possible to make API call to the provider. Something like this:

Socialite::api("/v1/users/me/contacts.json", array(
   "limit" => "5",
   "user_fields" => "id,display_name"
));

Regards,
Yancho

**Comment by DraperStudio** [comment]
Socialite is only meant to be used for authentication.

If you need to send requests use https://github.com/xing/xing-api-samples/tree/master/php or another API Client with the access token you obtained from the Socialite Authentication.
